import{a as E,S as w,i as s}from"./assets/vendor-DDdXnYQq.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const u of r.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&c(u)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();async function h(a,o){return(await E.get("https://pixabay.com/api/",{params:{key:"25786434-348adb767e319176b4ad356ea",q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o}})).data}const i={galleryEl:document.querySelector(".gallery"),formEL:document.querySelector(".form"),btnLoadMoreEl:document.querySelector(".btn-load-more"),loaderEl:document.querySelector(".loader")};function m(a){return a.map(e=>`<li class="photo-card">
          <a href="${e.largeImageURL}"><img src="${e.webformatURL}" alt="${e.tags}" />
          <div class="info">
            <p><b>Likes</b> <span>${e.likes}</span></p>
            <p><b>Views</b> <span>${e.views}</span></p>
            <p><b>Comments</b> <span>${e.comments}</span></p>
            <p><b>Downloads</b> <span>${e.downloads}</span></p>
          </div>
          </a>
        </li>`).join(`
`)}function v(){i.galleryEl.innerHTML=""}function y(){i.loaderEl.classList.remove("hidden")}function d(){i.loaderEl.classList.add("hidden")}function M(){i.btnLoadMoreEl.classList.remove("hidden")}function g(){i.btnLoadMoreEl.classList.add("hidden")}let f=new w(".gallery a");f.on("show.simplelightbox",function(){});let p,n,l=0;const S=15;i.formEL.addEventListener("submit",async a=>{a.preventDefault(),p=a.target.elements.searchText.value.trim(),n=1,v(),g(),y();try{const o=await h(p,n),e=m(o.hits);i.galleryEl.innerHTML=e,f.refresh(),l=Math.ceil(o.totalHits/S),d()}catch{s.error({title:"Error",position:"bottomRight"}),d()}L(),b(),a.target.reset()});i.btnLoadMoreEl.addEventListener("click",async()=>{n+=1,b(),L(),y();try{const a=await h(p,n),o=m(a.hits);i.galleryEl.insertAdjacentHTML("beforeend",o),f.refresh();const e=document.querySelector(".photo-card");if(e){const c=e.getBoundingClientRect().height;window.scrollBy({top:c*2,behavior:"smooth"})}d()}catch{s.error({title:"Error",position:"bottomRight"}),d()}});function b(){n<l?M():g()}function L(){l===0?s.error({title:"Sorry, there are no images matching your search query. Please try again!",position:"bottomRight"}):n===l?s.info({title:"We're sorry, but you've reached the end of search results.",position:"bottomRight"}):n===1&&s.info({title:`Max page: ${l}`,position:"bottomRight"})}
//# sourceMappingURL=index.js.map
