import{a as E,S as w,i as l}from"./assets/vendor-DDdXnYQq.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const p of o.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&i(p)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();async function f(r,t){return(await E.get("https://pixabay.com/api/",{params:{key:"25786434-348adb767e319176b4ad356ea",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}const a={galleryEl:document.querySelector(".gallery"),formEL:document.querySelector(".form"),btnLoadMoreEl:document.querySelector(".btn-load-more"),loaderEl:document.querySelector(".loader")};let h=new w(".gallery a");h.on("show.simplelightbox",function(){});function m(r,t){const n=r.map(i=>`<li class="photo-card">
          <a href="${i.largeImageURL}"><img src="${i.webformatURL}" alt="${i.tags}" />
          <div class="info">
            <p><b>Likes</b> <span>${i.likes}</span></p>
            <p><b>Views</b> <span>${i.views}</span></p>
            <p><b>Comments</b> <span>${i.comments}</span></p>
            <p><b>Downloads</b> <span>${i.downloads}</span></p>
          </div>
          </a>
        </li>`).join(`
`);t==="replace"?a.galleryEl.innerHTML=n:t==="append"&&a.galleryEl.insertAdjacentHTML("beforeend",n),h.refresh()}function v(){a.galleryEl.innerHTML=""}function y(){a.loaderEl.classList.remove("hidden")}function g(){a.loaderEl.classList.add("hidden")}function M(){a.btnLoadMoreEl.classList.remove("hidden")}function u(){a.btnLoadMoreEl.classList.add("hidden")}let d,s,c=0;const S=15;a.formEL.addEventListener("submit",async r=>{if(r.preventDefault(),d=r.target.elements.searchText.value.trim(),s=1,d===""){l.error({title:"Enter value",position:"bottomRight"});return}u(),v(),y();try{const t=await f(d,s);m(t.hits,"replace"),c=Math.ceil(t.totalHits/S)}catch{l.error({title:"Error",position:"bottomRight"})}finally{g(),L(),b()}r.target.reset()});a.btnLoadMoreEl.addEventListener("click",async()=>{s+=1,u(),L(),y();try{const r=await f(d,s);m(r.hits,"append");const t=document.querySelector(".photo-card");if(t){const n=t.getBoundingClientRect().height;window.scrollBy({top:n*2,behavior:"smooth"})}}catch{l.error({title:"Error",position:"bottomRight"})}finally{g(),b()}});function b(){s<c?M():u()}function L(){c===0?l.error({title:"Sorry, there are no images matching your search query. Please try again!",position:"bottomRight"}):s===c?l.info({title:"We're sorry, but you've reached the end of search results.",position:"bottomRight"}):s===1&&l.info({title:`Max page: ${c}`,position:"bottomRight"})}
//# sourceMappingURL=index.js.map
